### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.mesibo.api.JNIAPI.set_security(int)

### ISSUE THREAD

**Issue by kbansal1005** [mesibo/samples#58]
Hi,

I am trying to run app with Mesibo integrated on Android 10 and am getting this error:

[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.UnsatisfiedLinkError: No implementation found for void com.mesibo.api.JNIAPI.set_security(int) (tried Java_com_mesibo_api_JNIAPI_set_1security and Java_com_mesibo_api_JNIAPI_set_1security__I)
        at com.mesibo.api.JNIAPI.set_security(Native Method)
        at com.mesibo.api.Mesibo.setSecureConnection(SourceFile:2)
        at app.marketplace.com.marketplace.MainActivity.mesiboInit(MainActivity.kt:10)
        at app.marketplace.com.marketplace.MainActivity.access$mesiboInit(MainActivity.kt:1)
        at app.marketplace.com.marketplace.MainActivity$configureFlutterEngine$2.onMethodCall(MainActivity.kt:11)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:2)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:5)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Mesibo was running fine on the last build I made 20 days ago and I haven't changed any code related to Mesibo since then but when I am creating a build now, the app is crashing and throwing this error. The app is working fine uptill Android version 8.

Here are the specifics of my app:

compileSdkVersion 29
minSdkVersion 21
targetSdkVersion 29

Tested on Android OS: Android 7.1.1, 8.0, 10.0

Using: com.mesibo.api:mesibo:1.0.90

**Comment by mesibo** [comment]
Duplicate issue
