### ISSUE TITLE
Error StrictMode in Android 5.0

### ISSUE THREAD

**Issue by adisiji** [mesibo/samples#67]
Hi Mesibo Team !
I got this error when the app running in Android 5.0. It seems because you use deprecated Jacoco. Please read https://github.com/jacoco/jacoco/issues/113

```
E/StrictMode: NetworkOnMainThreadException happen in user version, Just give a traces
    java.lang.RuntimeException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1152)
        at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
        at java.net.InetAddress.getLocalHost(InetAddress.java:396)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.createSessionId(Agent.java:172)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:118)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
        at id.co.foo.bar.App.$jacocoInit(App.kt)
        at id.co.foo.bar.App.<init>(App.kt)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1606)
        at android.app.Instrumentation.newApplication(Instrumentation.java:995)
        at android.app.Instrumentation.newApplication(Instrumentation.java:980)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:574)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4754)
        at android.app.ActivityThread.access$1700(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

Thank you in advance !

**Comment by mesibo** [comment]
We do not know or use jacoco. We also do not see mesibo in the logs you have sent. Hence I am closing the ticket.
